[package]
name = "noir_spaceship"
type = "bin"
authors = [""]
compiler_version = ">=0.29.0"
version = "1.0.0"

[dependencies]

[tool.NodeGuardians]
part_1 = "Shield Calculations"
part_2 = "Survival Proof"