initial_shield = "10000"

shield_regen_percentage = "10"

asteroid_masses_positive = [
   "100", "2000", "200", "100",
   "100", "50", "50", "14"
]

asteroid_masses_negative = [
   "2000", "300", "200", "20",
   "15", "20", "1", "1"
]